#!/usr/bin/python

"""
wmiirc-python :: foolish attempt
"""

import wmii
import logging
import os
import socket
import plugins

#class Filter:
    #def filter(self, rec): return False

def main():
    logging.basicConfig(level=logging.DEBUG, filename = os.path.expandvars("$HOME/.wmii-hg/log"))


    hostname = socket.gethostname()


    wmii.apps['terminal'] = 'urxvtc'
    if hostname.find('divms') > -1:
        wmii.apps['terminal'] = 'gnome-terminal'

    if hostname in ['hannibal', 'baracus']:
        wmii.colors['normfg'] = '#FFFFFF'
        wmii.colors['normbg'] = '#222222'
        wmii.colors['normborder'] = '#333333'
        wmii.colors['focusfg'] = '#FFFFaa'
        wmii.colors['focusbg'] = '#007700'
        wmii.colors['focusborder'] = '#88ff88'

    volume = plugins.Volume()
    clock = plugins.Clock()

    wmii.register_plugin(clock)
    wmii.register_plugin(volume)

    wmii.mainloop()

if __name__ == '__main__':
    main()
