#!/usr/bin/python

"""
wmpy :: foolish attempt
"""

import wmii
import logging
import os
import socket
import plugins
import themes

#class Filter:
    #def filter(self, rec): return False

def main():
    logging.basicConfig(level=logging.DEBUG, filename = os.path.expandvars("$HOME/.wmii-hg/log"))

    hostname = socket.gethostname()

    wmii.apps['terminal'] = 'urxvtc'
    if hostname.find('divms') > -1:
        wmii.apps['terminal'] = 'gnome-terminal'

    wmii.set_theme(themes.default)
    if hostname in ['hannibal', 'baracus']:
        wmii.set_theme(themes.green)

    volume = plugins.Volume(name='805_volume_1')
    wmii.register_plugin(volume)

    volume = plugins.Volume(name='805_volume_2', device="PCM")
    wmii.register_plugin(volume)

    clock = plugins.Clock()
    wmii.register_plugin(clock)

    wmii.mainloop()

if __name__ == '__main__':
    main()
