#!/usr/bin/python

"""
wmpy :: foolish attempt
"""

import wmii
import logging
import os
import socket
import plugins
import themes

#class Filter:
    #def filter(self, rec): return False

def main():
    logging.basicConfig(level=logging.DEBUG, filename = os.path.expandvars("$HOME/.wmii-hg/log"))

    hostname = socket.gethostname()

    wmii.tagrules['Gran Paradiso'] = 'www'

    wmii.apps['terminal'] = 'urxvtc'
    if hostname.find('divms') > -1:
        wmii.apps['terminal'] = 'gnome-terminal'

    wmii.set_theme(themes.green)
    if hostname in ['hannibal', 'baracus']:
        wmii.set_theme(themes.klav)

    if hostname in ['murdock']:
        volume = plugins.Volume(name='805_volume', device="LineOut")
        wmii.register_plugin(volume)

        battery = plugins.Battery()
        wmii.register_plugin(battery)
    else:
        volume = plugins.Volume(name='805_volume_1')
        wmii.register_plugin(volume)

        volume = plugins.Volume(name='805_volume_2', device="PCM")
        wmii.register_plugin(volume)

    clock = plugins.Clock()
    wmii.register_plugin(clock)

    if hostname in ['baracus']:
        wmii.config['font'] =  '-artwiz-snap-*-*-*-*-*-*-*-*-*-*-*-*'
        mpd = plugins.MPD()
        wmii.register_plugin(mpd)

        cpu = plugins.CPU(name='750_cpu0', cpu=0)
        wmii.register_plugin(cpu)

        cpu = plugins.CPU(name='750_cpu1', cpu=1)
        wmii.register_plugin(cpu)

    weather = plugins.Weather()
    wmii.register_plugin(weather)

    wmii.mainloop()

if __name__ == '__main__':
    main()
